### ISSUE TITLE
Can `Let` blocks with multiple lines use `{ }` syntax?

### ISSUE THREAD

**Issue by cesartalves** [rubocop/rspec-style-guide#117]
I tried finding this on the guide but did not.

It's very common to see `let` blocks which are considerably long being broken in multiple lines.
```
let(:order) {
 # multi-line let
}
```

I have seen it in quite a few projects I've worked.
Is this acceptable?

**Comment by pirj** [comment]
The same rules as for the rest of Ruby code usually apply, but not always the with RSpec's DSL.
See https://github.com/rubocop/ruby-style-guide/issues/558 for DSL and parentheses, and also curly braces with multi-line block `expect` syntax are quite common:
```ruby
expect {
  some_lengthy_call
}.to receive(...)
```

Would you like to check among open-source projects? I can suggest grepping https://github.com/pirj/real-world-rspec
